project:
  type: website

website:
  page-navigation: true
  title: "Philadelphia R User Group"
  site-url: https://www.phillyrug.org

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Philadelphia R User Group Organizers, Cory Cutsail & Bomi Hong (2022)."

  sidebar:
    logo: images/openscapes_hex.png
    align: center
    tools:
      - icon: meetup
        href: https://www.meetup.com/meetup-group-rfxisjyh/
        text: "PhillyRUG Meetup"
      - icon: github
        href: https://github.com/PhillyRUG/
        text: "PhillyRUG Github"
      - icon: twitter
        href: https://twitter.com/PhillyRUG
        text: "PhillyRUG Twitter"

    style: "docked"
    search: true
    collapse-level: 2
    collapsed: true
    contents:
      - href: "index.qmd"
        text: Welcome
      - href: 'content/discord.qmd'
        text: Discord
      - section: Tidy Tuesday
        contents:
          - content/tt20220809.qmd
          - content/tt20221025.qmd
      - section: Journal Club
        contents:
          - content/jc_gas_20221108.qmd



format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - quarto

execute:
  freeze: auto
